### ISSUE TITLE
Request for UI

### ISSUE THREAD

**Issue by sneazy-ibo** [subrotokumar/kurumi#3]
Themes with Amoled and more customization if not planned alr would be great :)

**Comment by subrotokumar** [comment]
Hello, thank you for your interest in our project. We appreciate your feedback and suggestions. However, this is not the right place to request new features. Please use the discussion page instead, where you can share your ideas and opinions with other users and me. This will help us keep the issue page focused on bug reports and technical issues. Thank you for your understanding and cooperation. 😊

**Comment by subrotokumar** [comment]
Also, could you please elaborate more on the feature you are requesting? 
What is the problem you are trying to solve? How would the feature work and benefit the project? What are some possible challenges or drawbacks of implementing it? Please provide as much detail as possible, so that we can understand your perspective and evaluate your proposal. Thank you for your contribution. 👍
